### ISSUE TITLE
Make ActionType plugins context aware

### ISSUE THREAD

**Issue by maijs** [james-nesbitt/drupal-sapi2-prototype#32]
To declare which external data structures are required for `ActionType` plugins to work properly, it may be beneficial to add implementation of `ContextAwarePluginInterface` to said plugins. It will allow define data structure dependencies in plugin annotation. Example:

```
@ActionType(
  // ...
  context = {
    "node" = @ContextDefinition("entity:node", label = @Translation("Node"), required = FALSE)
  }
)
```

See how `UserRole` class [does it](https://api.drupal.org/api/drupal/core!modules!user!src!Plugin!Condition!UserRole.php/class/UserRole/8.1.x). 
See [`ContextAwarePluginInterface.php`](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Plugin%21ContextAwarePluginInterface.php/8.2.x)

**Comment by james-nesbitt** [comment]
Very good idea.  I will try to get this in place ASAP

**Comment by james-nesbitt** [comment]
27 days later I got #37 in place
